In [2]:
import cv2
import numpy as np
import face_recognition
import pandas as pd

In [3]:
data=pd.read_csv("datadetails.csv")
data.head(5)
row, col = data.shape
row

3

In [14]:
images=[]
for i in range(0,row):
    img_dir= str(data.iloc[i,1])
    print(img_dir)
    train_image=cv2.imread(img_dir)
    images.append(train_image)

/home/ran/Desktop/Kaldi AIMS Lab/FaceRecognition/database/1.jpg
/home/ran/Desktop/Kaldi AIMS Lab/FaceRecognition/database/2.jpg
/home/ran/Desktop/Kaldi AIMS Lab/FaceRecognition/database/3.jpg


In [15]:
def findencodings(images):
    encodeList=[]
    for img in images:
        train_image=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encode_train=face_recognition.face_encodings(train_image)[0]
        encodeList.append(encode_train)
    return encodeList   

In [16]:
encodeListKnown=findencodings(images)
print(len(encodeListKnown))

3


In [ ]:
cap = cv2.VideoCapture(0)

while True:
    success, img = cap. read()
    imgS= cv2.resize(img,(0,0), None, 0.25, 0.25)
    imgS=cv2.cvtColor(imgS,cv2.COLOR_BGR2RGB)
    facesCurFrame=face_recognition.face_locations(imgS)
    encodeCurFrame= face_recognition.face_encodings(imgS,facesCurFrame)
    for encodeFace, facLoc in zip(encodeCurFrame, facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis= face_recognition.face_distance(encodeListKnown, encodeFace)
        print(faceDis)
        matcheIndex= np.argmin(faceDis)
        print(matcheIndex)
        name = str(data.iloc[2,2])
        print(name)
        

[0.78244687 0.87863658 0.46043288]
2
nabid
[0.77646373 0.88271121 0.52535806]
2
nabid
[0.77629816 0.81089465 0.43884315]
2
nabid
[0.76441555 0.84179894 0.45332262]
2
nabid
[0.74484152 0.84919661 0.48413146]
2
nabid
[0.78282506 0.83508503 0.46270126]
2
nabid
[0.78470644 0.85222814 0.49006079]
2
nabid
[0.7906451  0.8854036  0.53662754]
2
nabid
[0.80539138 0.85039397 0.43969722]
2
nabid
[0.79959561 0.84722991 0.4676387 ]
2
nabid
[0.807539   0.84165912 0.44626892]
2
nabid
[0.82808285 0.8314456  0.45524353]
2
nabid
[0.77477694 0.85043786 0.44474105]
2
nabid
[0.79785461 0.84163292 0.48944428]
2
nabid
[0.79877278 0.845951   0.45734218]
2
nabid
[0.80723343 0.8302726  0.43945835]
2
nabid
[0.79866367 0.85168228 0.46790961]
2
nabid
[0.78780392 0.83501032 0.44989752]
2
nabid
[0.80933862 0.83240297 0.45130852]
2
nabid
[0.79410589 0.82722935 0.4634992 ]
2
nabid
[0.82519518 0.82166461 0.45013279]
2
nabid
[0.8256157  0.86051031 0.45806926]
2
nabid
[0.80312957 0.81991583 0.42464297]
2
nabid
[0.77361396

[0.87553308 0.88285125 0.52395872]
2
nabid
[0.83820023 0.87969823 0.52476325]
2
nabid
[0.83601151 0.88565812 0.53887909]
2
nabid
[0.87556445 0.89556693 0.54809371]
2
nabid
[0.85683629 0.87367197 0.53137852]
2
nabid
[0.84333273 0.87343225 0.54022914]
2
nabid
[0.87545192 0.89562783 0.54184812]
2
nabid
[0.84031842 0.83395699 0.49576479]
2
nabid
[0.80052375 0.83753618 0.46201336]
2
nabid
[0.82355998 0.82887219 0.5054799 ]
2
nabid
[0.76711365 0.8586737  0.48382137]
2
nabid
[0.76826435 0.85922874 0.50414986]
2
nabid
[0.79518119 0.87531727 0.44647102]
2
nabid
[0.77066673 0.8271623  0.45008228]
2
nabid
[0.75997407 0.85500501 0.4721466 ]
2
nabid
[0.75312702 0.83951606 0.47173159]
2
nabid
[0.76278417 0.85080416 0.41472937]
2
nabid
[0.77723311 0.87190133 0.43324709]
2
nabid
[0.80195404 0.86520195 0.43101985]
2
nabid
[0.78163375 0.86874555 0.45512543]
2
nabid
[0.79635105 0.86319404 0.48082675]
2
nabid
[0.78351554 0.83851443 0.45691913]
2
nabid
[0.79545222 0.84680575 0.44372074]
2
nabid
[0.74209982

[0.51952905 0.80642005 0.7471618 ]
0
nabid
[0.8011817  0.86027856 0.54372933]
2
nabid
[0.79486752 0.84133525 0.52362901]
2
nabid
[0.62079649 0.80656888 0.71736457]
0
nabid
[0.55309752 0.72120534 0.74236044]
0
nabid
[0.49331366 0.77131851 0.76894854]
0
nabid
[0.49343037 0.79816839 0.74071371]
0
nabid
[0.48477616 0.85107713 0.74845024]
0
nabid
[0.51057634 0.86668657 0.79472331]
0
nabid
[0.48221866 0.81953327 0.75027307]
0
nabid
[0.47005413 0.80883308 0.76862739]
0
nabid
[0.48755864 0.80993698 0.79865643]
0
nabid
[0.45837071 0.80462279 0.7859243 ]
0
nabid
[0.40819479 0.81393029 0.79308656]
0
nabid
[0.4572463  0.79798357 0.78085941]
0
nabid
[0.47112124 0.77829541 0.7382427 ]
0
nabid
[0.5107478  0.79707415 0.75507259]
0
nabid
[0.50961187 0.80877185 0.78254803]
0
nabid
[0.44762381 0.79976401 0.76375678]
0
nabid
[0.43675791 0.79603983 0.77918329]
0
nabid
[0.43825962 0.78938159 0.75960948]
0
nabid
[0.49298045 0.78814835 0.75890129]
0
nabid
[0.51866583 0.78314432 0.71612595]
0
nabid
[0.54239546

[0.41446926 0.82845506 0.78111594]
0
nabid
[0.42978376 0.81374313 0.77489445]
0
nabid
[0.44690138 0.81240605 0.76933643]
0
nabid
[0.47068168 0.80966819 0.76537811]
0
nabid
[0.49854876 0.79791826 0.75611534]
0
nabid
[0.5233338  0.79597352 0.75895317]
0
nabid
[0.52261706 0.79480242 0.7611175 ]
0
nabid
[0.50462229 0.81242225 0.75936976]
0
nabid
[0.46101631 0.82236028 0.76000302]
0
nabid
[0.41967765 0.82291093 0.76472458]
0
nabid
[0.42244094 0.82830804 0.78151745]
0
nabid
[0.41670642 0.83668434 0.78142345]
0
nabid
[0.41050134 0.83581757 0.78980761]
0
nabid
[0.40902414 0.81608392 0.77532535]
0
nabid
[0.43870373 0.82321536 0.76984222]
0
nabid
[0.51317172 0.81527768 0.7796144 ]
0
nabid
[0.49216887 0.78898232 0.7574629 ]
0
nabid
[0.41187532 0.80928551 0.80131327]
0
nabid
[0.43640184 0.81878727 0.78859822]
0
nabid
[0.52681287 0.75905607 0.74975706]
0
nabid
[0.54403648 0.73927715 0.74030085]
0
nabid
[0.5338567  0.76522032 0.73837517]
0
nabid
[0.45967886 0.75343923 0.76139399]
0
nabid
[0.46308971

[0.47327312 0.82299621 0.76060147]
0
nabid
[0.46691253 0.8287769  0.76605955]
0
nabid
[0.46595384 0.79855772 0.75357845]
0
nabid
[0.47574983 0.82654402 0.76354181]
0
nabid
[0.46230552 0.82379303 0.76759884]
0
nabid
[0.45825494 0.82872329 0.75981499]
0
nabid
[0.45070127 0.82021097 0.77115209]
0
nabid
[0.44137905 0.82522684 0.75171327]
0
nabid
[0.42640615 0.83504476 0.78118731]
0
nabid
[0.40842198 0.81412023 0.76888296]
0
nabid
[0.44954303 0.81826447 0.7956803 ]
0
nabid
[0.48103125 0.8004573  0.7767793 ]
0
nabid
[0.44924816 0.81480233 0.76531966]
0
nabid
[0.40699907 0.81520389 0.78989867]
0
nabid
[0.434472   0.80560668 0.79451692]
0
nabid
[0.45037207 0.80101223 0.7667403 ]
0
nabid
[0.45517092 0.79051102 0.76074677]
0
nabid
[0.42787096 0.8036924  0.77677251]
0
nabid
[0.44472046 0.80908528 0.77616053]
0
nabid
[0.44357435 0.80730646 0.76541203]
0
nabid
[0.46092529 0.82099278 0.79766637]
0
nabid
[0.4529677  0.8270733  0.79706886]
0
nabid
[0.41234613 0.80715789 0.79506112]
0
nabid
[0.41123268

[0.79116056 0.85610853 0.46943237]
2
nabid
[0.78341577 0.85496859 0.47882537]
2
nabid
[0.75893411 0.83258338 0.40895991]
2
nabid
[0.80194093 0.83831236 0.47013181]
2
nabid
[0.7599974  0.82177813 0.43509998]
2
nabid
[0.76741328 0.82816651 0.43209406]
2
nabid
[0.77793306 0.79943933 0.39914193]
2
nabid
[0.79555096 0.82937705 0.43194297]
2
nabid
[0.79226017 0.83934483 0.45448363]
2
nabid
[0.83379207 0.83283749 0.45907937]
2
nabid
[0.81822421 0.84578329 0.48798696]
2
nabid
[0.87997248 0.8762267  0.5262613 ]
2
nabid
[0.85959333 0.87416298 0.51097165]
2
nabid
[0.87050443 0.87731432 0.55419903]
2
nabid
[0.88213877 0.89252432 0.56718124]
2
nabid
[0.84322324 0.86786046 0.56804585]
2
nabid
[0.87114955 0.85068135 0.5731733 ]
2
nabid
[0.88699336 0.85353135 0.59203694]
2
nabid
[0.87616673 0.87798514 0.59838527]
2
nabid
[0.86264328 0.86335644 0.58341238]
2
nabid
[0.86885296 0.87946498 0.59037216]
2
nabid
[0.86236825 0.87761562 0.60971574]
2
nabid
[0.83914011 0.8724884  0.57522755]
2
nabid
[0.84721363

[0.54880781 0.80692557 0.78960459]
0
nabid
[0.51357865 0.78689379 0.78197725]
0
nabid
[0.50069267 0.80843119 0.79020171]
0
nabid
[0.45986463 0.8092066  0.77109608]
0
nabid
[0.41750266 0.83336463 0.78654986]
0
nabid
[0.41966472 0.83364584 0.80362068]
0
nabid
[0.43634142 0.81001283 0.79500952]
0
nabid
[0.43348452 0.81922085 0.80870677]
0
nabid
[0.38947981 0.83455786 0.78560579]
0
nabid
[0.42680323 0.84438977 0.8075575 ]
0
nabid
[0.43827182 0.82881068 0.7924936 ]
0
nabid
[0.4411748  0.80289539 0.77812753]
0
nabid
[0.46472611 0.82211516 0.77478071]
0
nabid
[0.46803667 0.82068266 0.76251788]
0
nabid
[0.45203927 0.8097459  0.76336868]
0
nabid
[0.4430163  0.82796268 0.78971806]
0
nabid
[0.44677726 0.79993301 0.77036733]
0
nabid
[0.44943807 0.81672162 0.79292656]
0
nabid
[0.40455769 0.81666845 0.81182406]
0
nabid
[0.43612102 0.78592201 0.77349647]
0
nabid
[0.46524439 0.80645031 0.79547767]
0
nabid
[0.42455973 0.81796433 0.76681635]
0
nabid
[0.49106722 0.85442232 0.82334282]
0
nabid
[0.45834904

[0.75619495 0.87648375 0.49551274]
2
nabid
[0.77296164 0.85338494 0.45458085]
2
nabid
[0.78984843 0.86843854 0.51110566]
2
nabid
[0.79200738 0.85602451 0.4800113 ]
2
nabid
[0.77713198 0.85223822 0.46035268]
2
nabid
[0.7867607  0.86088627 0.48530371]
2
nabid
[0.7902277  0.84641665 0.47988077]
2
nabid
[0.76820227 0.86674138 0.49698168]
2
nabid
[0.78476194 0.87008475 0.50356613]
2
nabid
[0.78213709 0.8704181  0.50299094]
2
nabid
[0.75762894 0.85354621 0.42454025]
2
nabid
[0.78536505 0.86565215 0.47235495]
2
nabid
[0.78357071 0.84438422 0.43761366]
2
nabid
[0.7852912  0.84431751 0.44308116]
2
nabid
[0.77185827 0.86775984 0.52049247]
2
nabid
[0.80010564 0.87654679 0.52576644]
2
nabid
[0.81983964 0.89300089 0.49276548]
2
nabid
[0.784633   0.88411696 0.51640236]
2
nabid
[0.8177199  0.85943967 0.50170657]
2
nabid
[0.7763139  0.88748364 0.50923167]
2
nabid
[0.78504293 0.85005188 0.49727609]
2
nabid
[0.79262063 0.85888721 0.47526596]
2
nabid
[0.7745204  0.84188982 0.43605512]
2
nabid
[0.77733336

In [10]:
cv2.imshow('webcam',img)
cv2.waitKey(1)

-1